#!/usr/bin/env bash
#
# Rejects a commit whose subject line exceeds the limit git_workflow.md sets.
#
# pr-lint validates the pull request title only, so nothing mechanically checked commit subjects
# and six of them passed review over the limit. This is what closes that gap. It is deliberately a
# tracked script rather than inline workflow YAML so the same code path CI runs can be run by hand
# against any range.
#
# Usage: scripts/check_commit_subjects.sh <revision-range>
#   e.g. scripts/check_commit_subjects.sh origin/develop..HEAD
#
# Merge commits are skipped: their subjects are generated by the merge button and carry the pull
# request title, which pr-lint already governs.

set -u

readonly LIMIT=80
readonly RANGE="${1:-}"

if [ -z "$RANGE" ]; then
    echo "usage: $0 <revision-range>" >&2
    exit 2
fi

status=0
offenders=0
checked=0

# Read the log into a variable and check git's exit status before trusting the result. Reading it
# through process substitution discarded that status, so an unresolvable range - a force-push race,
# a fork pull request whose base was never fetched, a shallow checkout - produced zero lines and
# was reported as "All 0 commit subjects are within the limit" with exit 0. The gate passed in
# exactly the situations where it could not do its job.
if ! log=$(git log --no-merges --format='%h|%s' "$RANGE"); then
    echo "::error::cannot resolve the revision range $RANGE" >&2
    exit 2
fi

while IFS='|' read -r sha subject; do
    [ -n "$sha" ] || continue
    checked=$((checked + 1))
    length=${#subject}
    if [ "$length" -gt "$LIMIT" ]; then
        offenders=$((offenders + 1))
        status=1
        # ::error:: renders as an annotation on the GitHub Actions run and as plain text elsewhere.
        echo "::error::$sha subject is $length characters; the limit is $LIMIT (target 72): $subject"
    fi
done <<EOF
$log
EOF

if [ "$status" -ne 0 ]; then
    echo "$offenders of $checked commit subjects in $RANGE exceed $LIMIT characters." >&2
    echo "Reword them with git rebase -i before pushing; the limit is in git_workflow.md." >&2
else
    echo "All $checked commit subjects in $RANGE are within $LIMIT characters."
fi

exit "$status"
